spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  web:
    resources:
      static-locations: file:assets/
  mvc:
    static-path-pattern: /assets/**

jwt:
  secret: dGhpc2lzbXlzZWNyZXRrZXlmb3JzaWduaW5nMTIzNDU2Nzg=
  expiration: 3600000
