spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/signaturedb
    username: postgres
    password: pwd123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

jwt:
  secret: dGhpc2lzbXlzZWNyZXRrZXlmb3JzaWduaW5nMTIzNDU2Nzg=
  expiration: 3600000